image: buildpack-deps:18.04-scm

job:
  only:
    refs:
      - gitlab
      - standalone
  parallel: 4

  before_script:
    - ./fix-hosts.sh && TESTSPACE_URL=$(cat testspace-url)
    - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C /usr/local/bin
    - testspace config url $TESTSPACE_URL
    - testspace -v
    - printenv
  
  script:
    - echo script
  
  after_script:
    - ./fix-hosts.sh # needed as this is separate context - see https://docs.gitlab.com/ee/ci/yaml/README.html#before_script-and-after_script
    - |
      for ((i=$CI_NODE_INDEX; i<=10; i=i+$CI_NODE_TOTAL))
      do
        export JOB=JOB-$i
        ./ts-time-push.sh
      done
