version: 1.0.{build}
configuration: Release

branches:
  only:
    - standalone

install:
  - call fix-hosts.bat && set /p TESTSPACE_URL=<testspace-url
  - appveyor DownloadFile https://testspace-client.s3.amazonaws.com/testspace-windows-dev.zip
  - 7z x -y testspace-windows-dev.zip
  - testspace config url "%TESTSPACE_URL%/s2technologies:testspace.test.ci"
  - testspace -v

# to run your custom scripts instead of automatic MSBuild
build_script:
  - echo build script

# to run your custom scripts instead of automatic tests
test_script:
  - set > printenv.txt
  - testspace config
  - print "%APPVEYOR_BUILD_FOLDER%/.testspace"

after_test:
  - set build_url="%APPVEYOR_URL%/project/%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%/builds/%APPVEYOR_BUILD_ID%"
  - echo %build_url%
  - testspace results.xml printenv.txt "standalone#appveyor.%APPVEYOR_BUILD_NUMBER%" --repo=git --build-url="%build_url%"
