version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    branches:
      only:
        - standalone
        - circle
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Install and configure Testspace client
          command: |
            ./fix-hosts.sh && TESTSPACE_URL=$(cat testspace-url)
            curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | sudo tar -zxvf- -C /usr/local/bin
            testspace config url $TESTSPACE_URL
            testspace -v
            printenv
      - run:
          name: Push to Testspace server
          command: |
            for ((i=$CIRCLE_NODE_INDEX+1; i<=10; i=i+$CIRCLE_NODE_TOTAL))
            do
              export JOB=JOB-$i
              ./ts-time-push.sh
            done
          when: always
